package org.synthcity.modulo_3;

public enum AlertaEvaluacion {
    TENDENCIA_NEGATIVA,
    CONTAMINACION_CRECIENTE,
    NECESIDAD_EXPANSION,
    COLAPSO_DETECTADO,
    BAJA_ACTIVIDAD,
    DEFICIT_SERVICIOS,
    DEFICIT_ENERGETICO,
    CONTAMINACION_ALTA,
    SATURACION
}
