package org.synthcity.modulo_3;

public enum TipoEstructuralCiudad {
    SIN_DATOS,
    RESIDENCIAL_DOMINANTE,
    INDUSTRIAL_DOMINANTE,
    ENERGETICA_DOMINANTE,
    SERVICIOS_DOMINANTE,
    TRANSPORTE_DOMINANTE,
    EQUILIBRADA
}

