package org.synthcity.modulo_2;

public enum EstadoSimulacion {
    CIUDAD_VACIA,
    SIN_BLOQUES_ACTIVOS,
    DEFICIT_ENERGETICO,
    DEFICIT_SERVICIOS,
    DESEQUILIBRIO_ESTRUCTURAL,
    COLAPSO_ENERGETICO,
    SATURACION_CRITICA,
    SIMULACION_ESTABLE,
    SIMULACION_INESTABLE
}
