package org.synthcity.modulo_2;

public enum EstadoSimulacion {
    EJECUTADA,
    CIUDAD_VACIA,
    SIN_BLOQUES_ACTIVOS,
    DEFICIT_ENERGETICO,
    DEFICIT_SERVICIOS,
    DESEQUILIBRIO_ESTRUCTURAL,
    SIMULACION_ESTABLE,
    SIMULACION_INESTABLE
}